### ISSUE TITLE
Expecting property name error when parsing js object

### ISSUE THREAD

**Issue by further-reading** [Nykakin/chompjs#14] opened 2020-08-28 14:11 UTC
Unable to parse the js below with parse_js_object using chompjs==1.0.16.

[test.txt](https://github.com/Nykakin/chompjs/files/5142503/test.txt)

I get the following error and traceback:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/venv/lib/python2.7/site-packages/chompjs/chompjs.py", line 34, in parse_js_object
    return json.loads(parsed_data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 283 (char 282)
```

**Comment by Nykakin** [comment] 2020-09-06 17:05
@further-reading 

Caused by Windows newlines in input. Fixed by https://github.com/Nykakin/chompjs/pull/15

Te fix will be included in 1.0.17, for now you can just strip these or use git version.

**Closed by Nykakin** 2020-09-06 17:05 UTC
